fixup! net: usb: rtl8150: Fix frame padding
Fixes commit 987fc69aff78b892e384abd51c982e69bba7c818 upstream.

The fix was based on commit 7d0a9989dad45a45e737a78a63c60c7a101fd1ae
upstream.

/home/thomas/a21s/kernel/qcom/sm8250/drivers/net/usb/rtl8150.c:707:10: error: comparison of distinct pointer types ('typeof (skb->len) *' (aka 'unsigned int *') and 'typeof (60) *' (aka 'int *')) [-Werror,-Wcompare-distinct-pointer-types]
  707 |         count = max(skb->len, ETH_ZLEN);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~

Change-Id: If4a118c06c11ee66b80042534300158ec1f2039b