iommu: iommu-debug: Fix incorrectly formatted string
This was probably trying to work around a checkpatch warning but it
tried to be too clever by half:

drivers/iommu/iommu-debug.c: In function '_size_to_string':
drivers/iommu/iommu-debug.c:407:50: error: left-hand operand of comma expression has no effect [-Werror=unused-value]

Fixes: d1cd595f848b ("iommu/arm-smmu: Merge of smmu changes from 4.14 to msm-kona")
Change-Id: Ic0dedbadaf2f8b8e4deb5e71a53af6a02f3d55ae
Signed-off-by: Jordan Crouse <jcrouse@codeaurora.org>