Revert "ARM: dts: hix5hd2: add wdg node"
This reverts commit 2f845444d4c8f61313dcd5f5b7793ac87ff31eb7.

"ARM: dts: hix5hd2: add wdg node" causes a build breakage due to
an undefined constatns:

Error: arch/arm/boot/dts/hisi-x5hd2.dtsi:374.22-23 syntax error

(Don't you just looove the dtc error messages? They are so informative!)

Signed-off-by: Olof Johansson <olof@lixom.net>