tracing, net: fix net tree and tracing tree merge interaction
Today's linux-next build (powerpc ppc64_defconfig) failed like this:

 In file included from net/core/skbuff.c:69:
 include/trace/skb.h:4: error: expected ')' before '(' token
 include/trace/skb.h:4: error: expected ')' before '(' token
 [...]

Caused by commit c3aae9b8425656bce4d26b1454e41989f273e6d7 ("tracing:
replace TP<var> with TP_<var>") from the tracing tree interacting with
commit 5a7676308c22db9d31654e87c2af36f6989cb198 ("Network Drop Monitor:
Add trace declaration for skb frees") from the net tree.

Acked-by: David S. Miller <davem@davemloft.net>
Signed-off-by: Ingo Molnar <mingo@elte.hu>