Revert "x86_64: Allow breakpoints to emulate call instructions"
This reverts commit e80906074cdf9a063809f5715a031c6edf42d1c7.

This is a preparation change for merging android-4.19.46 into
msm-4.19 branch.

This change leads to following errors during Usermode Linux Compilation:

/checker/work.refs/heads/msm-4.19/src/linux/kernel/arch/x86/include/asm/text-patching.h:44:6:
error: 'struct pt_regs' has no member named 'ip'
 S 12:31:00   regs->ip = ip;
 S 12:31:00       ^
 S 12:31:00
/checker/work.refs/heads/msm-4.19/src/linux/kernel/arch/x86/include/asm/text-patching.h:59:6:
error: 'struct pt_regs' has no member named 'sp'
 S 12:31:00   regs->sp -= sizeof(unsigned long);
 S 12:31:00       ^
 S 12:31:00
/checker/work.refs/heads/msm-4.19/src/linux/kernel/arch/x86/include/asm/text-patching.h:60:24:
error: 'struct pt_regs' has no member named 'sp'
 S 12:31:00   *(unsigned long *)regs->sp = val;
 S 12:31:00                         ^
 S 12:31:00
/checker/work.refs/heads/msm-4.19/src/linux/kernel/arch/x86/include/asm/text-patching.h:65:30:
error: 'struct pt_regs' has no member named 'ip'
 S 12:31:00   int3_emulate_push(regs, regs->ip - INT3_INSN_SIZE +
CALL_INSN_SIZE);
 S 12:31:00                               ^

Change-Id: Id67d4728096921773f48e4d7ebc08371557b2423
Signed-off-by: Ivaylo Georgiev <irgeorgiev@codeaurora.org>