linux-next: fix x86 tree build failure
Today's linux-next build (powerpc allyesconfig) failed like this:

drivers/char/agp/uninorth-agp.c:541: error: unknown field 'agp_destroy_paged' specified in initializer

Caused by commit f72f8840119339c3dbc95e434e512ba2dba0e9b6
("agp: enable optimized agp_alloc_pages methods").  A simple typo ...

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Ingo Molnar <mingo@elte.hu>