Revert "usb: host/sl811-hcd: fix sparse warning"
This reverts commit 9ff7bd91aaf983f5bff29bb5e0481402583d3303.

Commit 9ff7bd91aaf9 results in the following error when compiling
x86_64:allyesconfig.

sl811_cs.c:(.text+0x1d3cb72): undefined reference to `sl811h_driver'

Fixes: 9ff7bd91aaf9 ("usb: host/sl811-hcd: fix sparse warning")
Cc: Lad, Prabhakar <prabhakar.csengg@gmail.com>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>