[PATCH] Fix broken kernel headers preventing ARM build
As a result of a098b7c21a062a216831785f5b61e52bdccd1de6, the ARM
architecture is more or less unbuildable - only one defconfig appears
to build, with all others erroring out with:

	  CC      arch/arm/kernel/setup.o
	In file included from /home/rmk/git/linux-2.6-rmk/arch/arm/kernel/setup.c:22:
	/home/rmk/git/linux-2.6-rmk/include/linux/root_dev.h:7: warning: implicit declaration of function `MKDEV'
	...

Essentially, root_dev.h uses MKDEV and dev_t, but does not include any
headers which provide either of these definitions.  The reason it worked
previously is that linux/tty.h just happened to include the required
headers for linux/root_dev.h.

Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>
Signed-off-by: Linus Torvalds <torvalds@osdl.org>