Revert "mmc: tmio-mmc: Remove .set_pwr() callback from platform data"
This reverts commit e9dd6897870485ca6dd30b38ff576dc6dadbe13c, which
causes a build failure:

drivers/mfd/asic3.c:724:2: error: unknown field 'set_pwr' specified in initializer