HID: select NEW_LEDS for driver of Lenovo ThinkPad USB Keyboard with TrackPoint
commit 'HID: Driver for Lenovo Keyboard with Trackpoint'
(5fae1d5c96ef6815d9ca46860fbe4953b68b8b72) introduced a compiling error due to
unmetting dependency of CONFIG_LEDS_CLASS.

on i386:

ERROR: "led_brightness_set" [drivers/leds/led-class.ko] undefined!
ERROR: "leds_list" [drivers/leds/led-class.ko] undefined!
ERROR: "leds_list_lock" [drivers/leds/led-class.ko] undefined!

Reported-by: Randy Dunlap <rdunlap@xenotime.net>
Signed-off-by: Bryan Wu <bryan.wu@canonical.com>
Signed-off-by: Jiri Kosina <jkosina@suse.cz>