drm/sti: restore mode_fixup callback
Commit b9030654616b removed the mode_fixup because it was empty,
but 7f902582fe59 modified it to call drm_mode_set_crtcinfo()
instead.

Both commits are correct, but the merge of the two kept the nonempty
version without the reference to it, as shown by the gcc warning:

 drm/sti/sti_crtc.c:54:13: error: 'sti_crtc_mode_fixup' defined but not used

This restores the callback pointer to fix the merge.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Reverts: b9030654616b ("drm/sti: removed optional dummy crtc mode_fixup function.")
Fixes: 7f902582fe59 ("drm/sti: set CRTC modesetting parameters")
Fixes: 1ef60f3facd6 ("Merge branch '2016-02-26-st-drm-next' of http://git.linaro.org/people/benjamin.gaignard/kernel into drm-next")
Acked-by: Vincent ABRIOU <vincent.abriou@st.com>
Signed-off-by: Dave Airlie <airlied@redhat.com>