Revert "selftests: mm: fix map_hugetlb failure on 64K page size systems"
This reverts commit 9f844c80520870e4dbaac0f832b4d16fcb05cf2a which is commit
d8133f0429a003cd9e5fc100d4c77fd797a48189 upstream.

map_hugetlb.c:18:10: fatal error: vm_util.h: No such file or directory
   18 | #include "vm_util.h"
      |          ^~~~~~~~~~~
compilation terminated.

vm_util.h is not present in 4.19.y, as commit:d924dd01dab1 ("selftests:
vm: bring common functions to a new file") is not present in stable
kernels <=6.1.y

Signed-off-by: Harshit Mogalapalli <harshit.m.mogalapalli@oracle.com>
Cc: Shuah Khan <skhan@linuxfoundation.org>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>