microblaze idle: Fix compile error
Commit d338795 ("microblaze idle: delete pm_idle") introduced the following
compile error:

	arch/microblaze/kernel/process.c: In function 'cpu_idle':
	arch/microblaze/kernel/process.c:100: error: 'idle' undeclared (first use in this function)
	arch/microblaze/kernel/process.c:100: error: (Each undeclared identifier is reported only once
	arch/microblaze/kernel/process.c:100: error: for each function it appears in.)
	arch/microblaze/kernel/process.c:106: error: implicit declaration of function 'idle'

This patch fixes it.

Signed-off-by: Lars-Peter Clausen <lars@metafoo.de>
Acked-by: Len Brown <len.brown@intel.com>
Signed-off-by: Rafael J. Wysocki <rafael.j.wysocki@intel.com>