drm/msm/sde: Fix compile warnings
Fix the following compiler warning(s) from gcc 6.1.1 with -Werror enabled:

 drivers/gpu/drm/msm/sde/sde_kms.c:2672:2: error: ignoring return value of
   'drm_atomic_set_crtc_for_connector', declared with
   attribute warn_unused_result [-Werror=unused-result]

 drivers/gpu/drm/msm/sde/sde_kms.c:2674:2: error: ignoring return value of
   'drm_atomic_commit', declared with attribute warn_unused_result
   [-Werror=unused-result]

Change-Id: Ic0dedbade9323c5f6f52ff78f8c758b625082359
Signed-off-by: Jordan Crouse <jcrouse@codeaurora.org>