ASoC: Fix build error in twl4030.c
Fix the (likely cut-n-paste) error by commit
782112a68558e360cef8a7f45393fec767d0ca4f, which causes the error below:
  sound/soc/codecs/twl4030.c: In function 'twl4030_read_reg_cache':
  sound/soc/codecs/twl4030.c:152: error: 'cache' undeclared (first use in this function)

Signed-off-by: Takashi Iwai <tiwai@suse.de>