Revert "ARM: dts: mt8135: Add pinctrl/GPIO/EINT node for mt8135."
This reverts commit 3273b3fa96492854878b0ec4b4a9a9f9e6e653b2.

to fix a build error:

arch/arm/boot/dts/mt8135-pinfunc.h:18:40: fatal error: dt-bindings/pinctrl/mt65xx.h: No such file or directory

Signed-off-by: Arnd Bergmann <arnd@arndb.de>