tty/amiserial: Add missing argument for tty_unlock()
commit a6703d749329fe944fe96ba1ea85051fc5551196 ("tty_lock: Localise the lock")
missed that 11dd934b6a5de89af760083ff3de5f1f030bada4 ("drivers/tty/amiserial.c:
add missing tty_unlock") just added a new caller of tty_unlock():

drivers/tty/amiserial.c: In function ‘set_serial_info’:
drivers/tty/amiserial.c:1077: error: too few arguments to function ‘tty_unlock’

Signed-off-by: Geert Uytterhoeven <geert@linux-m68k.org>
Cc: Alan Cox <alan@linux.intel.com>
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>